services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:4173"   # Map host 5173 ? container 4173 (Vite default)
    depends_on:
      - backend
    restart: unless-stopped